name: 'slack'
description: 'slack message '
inputs:
  channel-id: # channel id to post message when using bot token
    description: 'Slack channel ID where message will be posted. Needed if using bot token'
    required: false
    default: C03Q50M03N3
  payload-file-path: # path to JSON payload to send to Slack via webhook
    description: 'path to JSON payload to send to Slack if webhook route. If not supplied, json from GitHub event will be sent instead. If payload is provided, it will take preference over this field'
    required: false
    default: ./.github/github-workflows/.github/slackMessage/slackMessage.json
  update-ts: # The timestamp of a previous message posted to update it instead of posting a new message
    description: 'The timestamp of a previous message posted. It will update the existing message instead of posting a new message'
    required: false
  message-type:
    description: init | newtask | taskstatus | end | cancelled | endlink
    required: true
  task-name:
    description: task name
    required: false
    default: none
  task-status:
    description: task status
    required: false
    default: none
  actor:
    description: build created by
    required: false
    default: none
  project-name: 
    description: project name
    required: false
    default: none
  bundle-version-code:
    description: bundle version code
    required: false
    default: none
  platform:
    description: target platform
    required: false
    default: none
  build-type:
    description: Production or Develop
    required: false
  commit-link:
    description: commit url
    required: false
    default: none
  action-link:
    description: action url
    required: false
    default: none
  slack-bot-token:
    description: slack bot tocken
    required: true
outputs:
  ts: # timestamp of message posted
    description: 'The timestamp on the message that was posted into Slack when using bot token'
    value: ${{ steps.slack.outputs.ts }}
runs:
  using: "composite"
  steps:
      - name: Updating message
        id: updating
        shell: bash
        run: | 
          echo "${{inputs.build-type}}"
          echo "${{inputs.message-type}}"
          bash ./.github/github-workflows/.github/actionsUtils/updateMessage.sh "${{inputs.message-type}}" "${{inputs.task-name}}" "${{inputs.task-status}}" "${{inputs.actor}}" "${{inputs.project-name}}" "${{inputs.bundle-version-code}}" "${{inputs.platform}}" "${{inputs.build-type}}" "${{inputs.commit-link}}" "${{inputs.action-link}}" "${{inputs.channel-id}}" "${{inputs.payload-file-path}}" "${{inputs.update-ts}}"
        
   # Slack notification message 
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          update-ts: ${{ inputs.update-ts }}
          channel-id: ${{ inputs.channel-id}}
          payload-file-path: ${{ inputs.payload-file-path }}
        env:
          SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
