name: testWorkflow
on:
    workflow_dispatch:
      inputs:
        PROJECT_NAME:
          required: true
          type: string
        TARGET_PLATFORM:
          required: true
          type: string
        BUILD_TYPE:
          required: true
          type: string

jobs:
  # slack:
  #   name: slack
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: log
  #     run: echo ${{toJson(github)}}
  #   - name: Send GitHub Action data to a Slack workflow
  #     uses: slackapi/slack-github-action@v2.0.0
  #     with:
  #       payload-file-path: ${{toJson(github.event.workflow)}}
  #       webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
  #       webhook-type: webhook-trigger
  header:
    name: Set Header
    runs-on: ubuntu-latest
    steps:
      - name: send headrers
        run: |
          curl -X POST https://hooks.slack.com/triggers/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 \
            -H "Content-Type: application/json" \
            -d '{
              "project_name": "${{ inputs.PROJECT_NAME }}",
              "target_platform": "${{ inputs.TARGET_PLATFORM }}",
              "build_type": "${{ inputs.BUILD_TYPE }}"
            }'
  job1:
    name: Job-1
    runs-on: ubuntu-latest
    needs: header
    steps:
      - name: Tag commit1
        run: echo "job1"
      - name: Tag commit2
        run: echo "job1 step2"
  job2:
    name: Job-2
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Tag commit3
        run: echo "job2"
  job3:
    name: Job-3
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Tag commit4
        run: echo "job3"
    
  job4:
    name: Job-4
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - name: Tag commit5
        run: echo "job4"
  # job5:
  #   name: Job-5
  #   runs-on: ubuntu-latest
  #   needs: job4
  #   steps:
  #     - name: Tag commit
  #       run: echo "job5"
  # job6:
  #   name: Job-6
  #   runs-on: ubuntu-latest
  #   needs: job5
  #   steps:
  #     - name: Tag commit
  #       run: echo "job6"

      
