
on:
    workflow_dispatch:
      inputs:
        TAG_NAME:
          description: 'tag name'
          required: true
          default: '0.0.0'
          type: string
        BUILD_TYPE:
          description: 'build type'
          required: true
          default: 'Development'
          type: choice
          options:
          - Development
          - Production

jobs:
  preparing-environment:
    name: preparing runner
    runs-on: ubuntu-latest
    steps:
      - name: Tag commit
        if: ${{inputs.BUILD_TYPE == 'Production'}}
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "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"
          tag: "${{inputs.TAG_NAME}}"
          commit-sha: ${{github.sha}}

      
