name: testWorkflow
on: push

jobs:
  check-modified-files:
    name: preparing runner
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - name: check-diff
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "^carpeta2/"; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
      
      - name: log
        if: steps.check-diff.outputs.changes == 'true'
        run : print true

