
on:
    workflow_dispatch:

jobs:
  job1:
    name: Job-1
    runs-on: ubuntu-latest
    steps:
      - name: Tag commit
        run: echo "job1"
  job2:
    name: Job-2
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Tag commit
        run: echo "job2"
  job3:
    name: Job-3
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Tag commit
        run: echo "job3"
    
  job4:
    name: Job-4
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - name: Tag commit
        run: echo "job4"
  job5:
    name: Job-5
    runs-on: ubuntu-latest
    needs: job4
    steps:
      - name: Tag commit
        run: echo "job5"
  job6:
    name: Job-6
    runs-on: ubuntu-latest
    needs: job5
    steps:
      - name: Tag commit
        run: echo "job6"

      
