name: Monitor Workflow Execution

on:
  workflow_run:
    workflows: ["testWorkflow"]  # Reemplaza con el nombre del otro workflow
    types:
      - requested

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener ID del último workflow en ejecución
        run: |

          WORKFLOW_ID=${{github.event.workflow.id}}

          echo "ID del workflow monitoreado: $WORKFLOW_ID"
          echo "WORKFLOW_ID=$WORKFLOW_ID" >> $GITHUB_ENV

          - name: Monitorear jobs en ejecución
          run: |
            STATUS="in_progress"
  
            while [[ "$STATUS" == "in_progress" || "$STATUS" == "queued" ]]; do
              sleep 10  # Esperar 10 segundos antes de verificar nuevamente
  
              JOBS_JSON=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                  -H "Accept: application/vnd.github.v3+json" \
                  "https://api.github.com/repos/${{ github.repository }}/actions/runs/$WORKFLOW_ID/jobs")
  
              echo "$JOBS_JSON"
  
              STATUS=$(echo "$JOBS_JSON" | jq -r '[.jobs[].status] | if all(. == "completed") then "completed" else "in_progress" end')
  
            done
  
          - name: Obtener estado final del workflow
            run: |
                CONCLUSION=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    "https://api.github.com/repos/${{ github.repository }}/actions/runs/$WORKFLOW_ID" | jq -r '.conclusion')
    
                echo "✅ El workflow finalizó con estado: $CONCLUSION"
