name: Observer
#miguelangelgil/testWORKFLOW/.github/workflows/main.yml@main
on:
  workflow_run:
    workflows: ["testWorkflow"]
    types:
      - completed
      - requested
      - in_progress
    
jobs:
    notify:
        name: notify
        runs-on: ubuntu-latest
        steps:
        - name: notify
          run: echo "🔔 *Workflow:* ${{ github.event.workflow }} \n📜 *Estado:* ${{ github.event.action }} \n🔗 *Detalles:* ${{ github.event.workflow_run.html_url }}"
    # call-next-workflow:
    #     uses: miguelangelgil/testActionObserver/.github/workflows/observer.yml@main
    #     with:
    #         WORKFLOW: ${{ github.event.workflow }}
    #         STATUS: ${{ github.event.action }}
    #         DETAILS: ${{ github.event.workflow_run.html_url }}