name: Observer
on:
  workflow_run:
    workflows: ["testWorkflow"]
    types:
      - completed
      - requested
      - in_progress
    
jobs:
    notify:
        name: notify
        runs-on: ubuntu-latest
        steps:
            - name: Modificar y enviar webhook
              run: |
                curl -X POST -H 'Content-type: application/json' --data '{
                    "custom_event": "workflow_completed",
                    "workflow_name": "${{ github.workflow }}",
                    "repository": "${{ github.repository }}",
                    "status": "${{ github.event.workflow_run.conclusion }}"
                }' ${{ secrets.SLACK_WEBHOOK_URL }}