name: Observer
#miguelangelgil/testWORKFLOW/.github/workflows/main.yml@main
on:
  workflow_run:
    workflows: ["testWorkflow"]
    types:
      - completed
    
jobs:
    call-next-workflow:
        uses: miguelangelgil/testActionObserver/.github/workflows/observer.yml@main
        with:
            WORKFLOW: ${{ github.workflow }}
            STATUS: ${{ github.event.workflow_run.conclusion }}
            DETAILS: ${{ github.event.workflow_run.html_url }}